# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.7

services:
  - postgresql

install:
  #- pip install tox-travis
  - pip install -r requirements-dev.txt

before_script:
  - cp .env.example .env
  - psql -c 'create database travis_ci_test;' -U postgres
  - flask db migrate
  - flask db upgrade

script:
  - pytest

after_success:
  - git config --global user.name "Simonbelete"
  - git config --global user.email "simonbelete@gmail.com"
  - semantic-release publish
