"""Creadential Model and Relation between User Model.

Revision ID: 0aa19aacbf3d
Revises: 
Create Date: 2020-08-29 13:25:39.302726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa19aacbf3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credentials', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('credentials_user_id_key', 'credentials', type_='unique')
    op.create_foreign_key(None, 'credentials', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.create_unique_constraint('credentials_user_id_key', 'credentials', ['user_id'])
    op.alter_column('credentials', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
