"""Permission Model.

Revision ID: 4d810d53b202
Revises: 99fea065902c
Create Date: 2020-09-10 05:05:07.480536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d810d53b202'
down_revision = '99fea065902c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
